name: Sync OpenAPI spec from Artemis

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 * * * *"
  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download OpenAPI file
        run: |
          curl -o openapi.yaml \
            https://raw.githubusercontent.com/ls1intum/Artemis/develop/openapi/openapi.yaml

      - name: Copy file
        run: |
          mkdir -p Sources/GeneratedServices
          mv openapi.yaml Sources/GeneratedServices/openapi.yml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update OpenAPI spec"
          branch: sync-openapi
          title: "`Development`: Sync OpenAPI spec"
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
